#!/usr/bin/env bash

SIZE=8
while getopts i:o:s:n:e: OPTION; do
	case $OPTION in
	i)
		INPUT=$OPTARG
		filename=$(basename "$INPUT")
		OUTPUT="$(dirname "$INPUT")"
		EXT=${filename#*.}
		;;
	o)
		OUTPUT=$OPTARG
		;;
	s)
		SIZE=$OPTARG
		;;
	n)
		NAME=$OPTARG
		;;
	e)
		EXT=$OPTARG
		;;
	\?)
		echo "[!] Error: Wrong use of flags"
		echo "Use ffcompress to get full help" >&2
		exit 1
		;;
	esac
done

if test -f "$INPUT" && test -d "$OUTPUT"; then
	outputname="${OUTPUT}/${filename%.*}-${SIZE}mb.${EXT}"
	if [ "$NAME" != "" ]; then
		outputname="${OUTPUT}/${NAME}.${EXT}"
	fi
	target_size=$(( $SIZE * 1000 * 1000 * 8 ))
	length=`ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$INPUT"`
	length_round_up=$(( ${length%.*} + 1 ))
	total_bitrate=$(( $target_size / $length_round_up ))
	audio_bitrate=$(( 128 * 1000 ))
	video_bitrate=$(( $total_bitrate - $audio_bitrate ))
	ffmpeg -i "$INPUT" -b:v $video_bitrate -maxrate:v $video_bitrate -bufsize:v $(( $target_size / 20 )) -b:a $audio_bitrate "$outputname"
else
	echo "FFCOMPRESS USAGE:"
	echo "   -i   input video file"
	echo "   -o   output video directory [default: input file dir]"
	echo "   -s   exported video maximum size [mb, default: 8]"
	echo "   -n   exported video name [default: FILENAME-Xmb]"
	echo "   -e   extension of exported video file"
fi
